import Head from 'next/head'
import { getGallery } from '../lib/flickr'
import GalleryCategories from '../components/GalleryCategories'
import GalleryIntro from '../components/GalleryIntro'
import GalleryImage from '../components/GalleryImage'

export default function Gallery({ images, gallery }) {
  return (
    <div>
      <Head>
        <title>{ `Flickr gallery || ${gallery.title}` }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GalleryIntro gallery={gallery}/>
      
      <div className="px-4 max-w-screen-2xl mx-auto">
        <GalleryCategories />
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 gap-y-12">
          { images.map((photo, index) => {
            return (
              <GalleryImage key={index} image={photo} index={index} />
            )
          })}
        </div>
      </div>

      <div>
        <button>Load more</button>
      </div>
    </div>
  )
}

export async function getStaticProps(context) {
  const data = await getGallery();

  const images = data?.photos?.photo || [];
  const gallery = data?.gallery || {};

  return {
    props: {
      images,
      gallery: {
        title: gallery?.title?._content || 'Flickr gallery',
        id: gallery?.id,
        user: gallery?.username,
        views: gallery?.count_views,
        count: gallery?.count_total
      }
    },
  }
}